[server]
port = 8081

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
pass = "ADMIN@forlty1314"
dbName   = "wyatt"
charset = "utf8mb4"
pool = 100

[redis]
host = "127.0.0.1"
port = 6379
pass = ""
pool = 20
dbName = 1

[mongo]
host = "127.0.0.1"
port = 27017
user = ""
pass = ""
pool = 50